config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"
  get 'welcome/index'
  resources :managefiles
  resources :incidentmanagements
  resources :incidentfiles
  resources :incidents
  resources :criticalities
  resources :applicationoperators
  resources :userareas
  resources :userapplications
  resources :applicationclients
  resources :areas
  resources :applications
  resources :userclients
  resources :clients
  resources :users
  resources :roles
  resources :vistaroles
  resources :vistaclientes
  resources :vistareportes
  resources :vistagestions
  get '/user/client/:id', to: 'users#user_client_index', as: "user_client_index"
  post '/user/client/:id', to: 'users#user_client_create', as: "user_client_create"
  get '/user/client/delete/:id', to: 'users#user_client_destroy', as: "user_client_destroy"

  get '/user/area/:id', to: 'users#user_area_index', as: "user_area_index"
  post '/user/area/:id', to: 'users#user_area_create', as: "user_area_create"
  get '/user/area/delete/:id', to: 'users#user_area_destroy', as: "user_area_destroy"
  
  get '/user/application/:id', to: 'users#user_application_index', as: "user_application_index"
  post '/user/application/:id', to: 'users#user_application_create', as: "user_application_create"
  get '/user/application/delete/:id', to: 'users#user_application_destroy', as: "user_application_destroy"

  get '/application/operator/:id', to: 'users#application_operator_index', as: "application_operator_index"
  post '/application/operator/:id', to: 'users#application_operator_create', as: "application_operator_create"
  get '/application/operator/delete/:id', to: 'users#application_operator_destroy', as: "application_operator_destroy"

  get '/client/application_client/:id', to: 'clients#client_application_client_index', as: "client_application_client_index"
  post '/client/application_client/:id', to: 'clients#client_application_client_create', as: "client_application_client_create"
  get '/client/application_client/delete/:id', to: 'clients#client_application_client_destroy', as: "client_application_client_destroy"

  devise_for :logins, controllers: {
    sessions: 'logins/sessions',
    registrations: 'logins/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/incidentmanagement.rb
class Incidentmanagement < ApplicationRecord
  validates :datereport, :presence => true
  validates :description, :presence => true
  belongs_to :user
  belongs_to :incident
  has_many :managefiles
end

app/controllers/incidentmanagements_controller.rb
class IncidentmanagementsController < ApplicationController
  before_action :authenticate_login!
  before_action :authenticate_role_user
  before_action :set_incidentmanagement, only: [:show, :edit, :update, :destroy]

  # GET /incidentmanagements
  # GET /incidentmanagements.json
  def index
    @incidentmanagements = Incidentmanagement.all
  end

  # GET /incidentmanagements/1
  # GET /incidentmanagements/1.json
  def show
  end

  # GET /incidentmanagements/new
  def new
    @incidentmanagement = Incidentmanagement.new
  end

  # GET /incidentmanagements/1/edit
  def edit
  end

  # POST /incidentmanagements
  # POST /incidentmanagements.json
  def create
    @incidentmanagement = Incidentmanagement.new(incidentmanagement_params)

    respond_to do |format|
      if @incidentmanagement.save
        format.html { redirect_to @incidentmanagement, notice: 'Incidentmanagement was successfully created.' }
        format.json { render :show, status: :created, location: @incidentmanagement }
      else
        format.html { render :new }
        format.json { render json: @incidentmanagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidentmanagements/1
  # PATCH/PUT /incidentmanagements/1.json
  def update
    respond_to do |format|
      if @incidentmanagement.update(incidentmanagement_params)
        format.html { redirect_to @incidentmanagement, notice: 'Incidentmanagement was successfully updated.' }
        format.json { render :show, status: :ok, location: @incidentmanagement }
      else
        format.html { render :edit }
        format.json { render json: @incidentmanagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidentmanagements/1
  # DELETE /incidentmanagements/1.json
  def destroy
    @incidentmanagement.destroy
    respond_to do |format|
      format.html { redirect_to incidentmanagements_url, notice: 'Incidentmanagement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def incident_incidentmanagement_index
    @user = User.find(params[:id])
    @userclients = Userclient.where("user_id = ?", @user.id)
    @clients = Client.all
    @userclient = Userclient.new
    render "userclients/index"
  end

   def incident_incidentmanagement_create
    @clientuser = Userclient.new(userclient_params)
    if @clientuser.save
      @user = User.find(params[:id])
      redirect_to user_client_index_path(@user.id)
    else
      render json: { error: @clientuser.errors.full_messages }, status: :bad_request
    end
  end

  def incident_incidentmanagement_destroy
    @userclient = Userclient.find(params[:userclient_id])
    if @userclient.destroy
      @user = User.find(params[:id])
      redirect_to user_client_index_path(@user.id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incidentmanagement
      @incidentmanagement = Incidentmanagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incidentmanagement_params
      params.require(:incidentmanagement).permit(:user_id, :incident_id, :datereport, :description, :state)
    end

    def authenticate_role_user
      unless current_login.user.role_id == 1
        redirect_to root_path
      end
    end
end

app/helpers/incidentmanagements_helper.rb
module IncidentmanagementsHelper
end

app/views/incidentmanagements/_form.html.erb
<br/><br/><br/>
<div class="container">
  <!-- The Modal -->
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
 <!-- Modal Header -->
    <div class="modal-header">
      <h4 class="modal-title"><kbd>Gestiona incidencias</kbd></h4>
    </div>
<!-- Modal body -->
  <div class="modal-body">
    <div class="modal-content tabcontent">
        <div class="dialog">
<%= simple_form_for(@incidentmanagement) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
<form class="form-inline">
  <label class="form-group col-md-2">
    <%= f.association :user %>
  </label>

  <label class="form-group col-md-2">
    <%= f.association :incident, label_method: :id %>
  </label>

  <label class="form-group col-md-7">
    <%= f.input :datereport %>
  </label>
 
 <label class="form-group col-md-3">
      <%= f.label :state%>
      <%= f.select :state, options_for_select([['Activo', true], ['Inactivo', false]]) %>
  </label>
  
&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;

  <label class="form-group col-md-5">
     <%= f.input :description %>
  </label>


  <label class="form-group">
    <%= f.button :submit, class:"btn btn-info" %>

    <%= link_to 'Regresar', vistagestions_path, class:"btn btn-info" %>
  </label>

<% end %>
       </form>
      </div>
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/incidentmanagements/edit.html.erb
<br/><br/><br/>
<div class="container">
  <!-- The Modal -->
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
 <!-- Modal Header -->
    <div class="modal-header">
      <h4 class="modal-title"><kbd>Gestiona incidencias</kbd></h4>
    </div>
<!-- Modal body -->
  <div class="modal-body">
    <div class="modal-content tabcontent">
        <div class="dialog">
<%= simple_form_for(@incidentmanagement) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
<form class="form-inline" method="post">
  <label class="form-group col-md-4">
    <%= f.association :user %>
  </label>

  <label class="form-group col-md-4">
    <%= f.association :incident, label_method: :id %>
  </label>

  <label class="form-group col-md-8">
    <%= f.input :datereport %>
  </label>
 
 <label class="form-group col-md-3">
      <%= f.label :state%>
      <%= f.select :state, options_for_select([['Activo', true], ['Inactivo', false]]) %>
  </label>
  

  <label class="form-group col-md-5">
     <%= f.input :description %>
  </label>


  <label class="form-group">
    <%= f.button :submit, class:"btn btn-info" %>
    <%= link_to 'Regresar', vistagestions_path, class:"btn btn-info" %>
  </label>

<% end %>
       </form>
      </div>
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/incidentmanagements/index.html.erb
<br/><br/><br/>
  <h1 style="color: #6c757d;">Gestión incidencias</h1>
    <div class="tab">
    <button class="tablinks active" onclick="openLink(event, 'Consulta incidencia')"><%= link_to 'Consulta incidencia', incidents_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Estadistica')"><%= link_to 'Estadistica', style: "color:rgb(23, 162, 184);" %></button>
  </div>
<br/>
<%= notice%>
 <br/><br/>

<div class="modal-content text-center">
<div class="table-responsive">
<table class="table">
<thead>
  <div class="row">
    <tr class="success btn-info active justify-content-center">
    <th colspan="3">Gestionar</th>
      <th>Usuario</th>
      <th>Incidencia</th>
      <th>Fecha</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </div>
</thead>

  <% @incidentmanagements.each do |incidentmanagement| %>

  <tbody>
    <div class="row">
      <tr class="text-center">
        <td colspan="3"><%= link_to incidentmanagement.id, incidentmanagement_path(incidentmanagement), class:"btn btn-info active"%></td>
        <td><%= incidentmanagement.user.name %></td>
        <td><%= incidentmanagement.incident.id %></td>
        <td><%= incidentmanagement.datereport %></td>
        <td><%= incidentmanagement.description %></td>
        <td>
          <% if incidentmanagement.state %>
             <img src="/img/estado_activo_24.png" alt="Activo" />
          <% else %>           
             <img src="/img/estado_falso_24.png" alt="Inactivo" />
          <% end %>
        </td>
        <td>
          <%= link_to edit_incidentmanagement_path(incidentmanagement) do %>
            <%= image_tag "/img/edit_24.png", :title=>"Editar" %>
          <% end %>
          &nbsp; &nbsp;
           <%= link_to incidentmanagement, method: :delete, data: { confirm: 'Desea eliminar?', remote: true } do %>
                <%= image_tag "/img/eliminar_24.png", :title=>"Eliminar" %>
           <% end %>
        </td>
       </tr>
      </div>
      </tbody>

    <% end %>
</table>
</div>
</div>

app/views/incidentmanagements/new.html.erb
<br/><br/><br/>
  <h1 style="color: #6c757d;">Gestión incidencia</h1>
    <div class="tab">
    <button class="tablinks active" onclick="openLink(event, 'Gestión incidencia')"><%= link_to 'Gestiona incidencia', new_incident_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Consulta incidencia')"><%= link_to 'Consulta incidencia', incidentmanagements_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Estadistica')"><%= link_to 'Estadistica', style: "color:rgb(23, 162, 184);" %></button>
  </div>
<%= notice%>
<%= render 'form', incidentmanagement: @incidentmanagement %>

app/views/incidentmanagements/show.html.erb
<br/><br/><br/>
  <h1 style="color: #6c757d;">Gestión incidencia</h1>
    <div class="tab">
    <button class="tablinks active" onclick="openLink(event, 'Gestiona incidencia')"><%= link_to 'Gestiona incidencia', @incidentmanagements_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Consulta incidencia')"><%= link_to 'Consulta incidencia', incidentmanagements_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Estadistica')"><%= link_to 'Estadistica', style: "color:rgb(23, 162, 184);" %></button>
  </div>
<%= notice%>
<br/><br/>

<div class="modal-content text-center">
<div class="table-responsive">
  <table class="table">

    <thead>
      <div class="row">
        <tr class="success btn-info active justify-content-center">
          <th colspan="2">Gestión ticket</th>
          <th>Usuario</th>
          <th>Incidencia</th>
          <th>Fecha/Hora</th>
          <th>Descripción</th>
          <th>Estado</th>
        </tr>
      </div>
    </thead>

    <tbody>
      <div class="row">
      <tr class="text-center">
        <td colspan="2"><%= @incidentmanagement.id%></td>
        <td><%= @incidentmanagement.user.name%></td>
        <td><%= @incidentmanagement.incident.id%></td>
        <td><%= @incidentmanagement.datereport%></td>
        <td><%= @incidentmanagement.description%></td> 
        <td>
          <% if @incidentmanagement.state %>
             <img src="/img/estado_activo_24.png" alt="Activo" />
          <% else %>           
             <img src="/img/estado_falso_24.png" alt="Inactivo" />
          <% end %>
        </td>
        </tr>
      </div>
    </tbody>
  </table>
</div>
</div>

<label class="form-group">
  <%= link_to 'Editar', edit_incidentmanagement_path(@incidentmanagement), class: "btn btn-info btn-md" %>
  <%= link_to 'Regresar', incidentmanagements_path, class: "btn btn-info btn-md" %>
</label>