config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"
  get 'welcome/index'
  resources :managefiles
  resources :incidentmanagements
  resources :incidentfiles
  resources :incidents
  resources :criticalities
  resources :applicationoperators
  resources :userareas
  resources :userapplications
  resources :applicationclients
  resources :areas
  resources :applications
  resources :userclients
  resources :clients
  resources :users
  resources :roles
  resources :vistaroles
  resources :vistaclientes
  resources :vistareportes
  resources :vistagestions
  get '/user/client/:id', to: 'users#user_client_index', as: "user_client_index"
  post '/user/client/:id', to: 'users#user_client_create', as: "user_client_create"
  get '/user/client/delete/:id', to: 'users#user_client_destroy', as: "user_client_destroy"

  get '/user/area/:id', to: 'users#user_area_index', as: "user_area_index"
  post '/user/area/:id', to: 'users#user_area_create', as: "user_area_create"
  get '/user/area/delete/:id', to: 'users#user_area_destroy', as: "user_area_destroy"
  
  get '/user/application/:id', to: 'users#user_application_index', as: "user_application_index"
  post '/user/application/:id', to: 'users#user_application_create', as: "user_application_create"
  get '/user/application/delete/:id', to: 'users#user_application_destroy', as: "user_application_destroy"

  get '/application/operator/:id', to: 'users#application_operator_index', as: "application_operator_index"
  post '/application/operator/:id', to: 'users#application_operator_create', as: "application_operator_create"
  get '/application/operator/delete/:id', to: 'users#application_operator_destroy', as: "application_operator_destroy"

  get '/client/application_client/:id', to: 'clients#client_application_client_index', as: "client_application_client_index"
  post '/client/application_client/:id', to: 'clients#client_application_client_create', as: "client_application_client_create"
  get '/client/application_client/delete/:id', to: 'clients#client_application_client_destroy', as: "client_application_client_destroy"

  devise_for :logins, controllers: {
    sessions: 'logins/sessions',
    registrations: 'logins/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :applicationclients
    has_many :applicationoperators
end

app/models/area.rb
class Area < ApplicationRecord
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :userareas
    has_many :incidents
end

app/models/client.rb
class Client < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    validates :name, :presence => true
    validates :nit, :presence => true
    validates :addres, :presence => true
    validates :telephone, :presence => true
    validates :nit, uniqueness: true
    validates :name, uniqueness: true
    has_many :userclients
    has_many :applicationclients
    has_many :userapplications
end

app/models/criticality.rb
class Criticality < ApplicationRecord

    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :incidents
    has_many :criticalities
end

app/models/incident.rb
class Incident < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :datereport, :presence => true
  validates :description, :presence => true
  belongs_to :area
  belongs_to :userapplication
  belongs_to :user
  belongs_to :criticality
  has_many :incidentfiles
  has_many :incidentmanagements
end

app/models/incidentfile.rb
class Incidentfile < ApplicationRecord
  belongs_to :incident
end

app/models/login.rb
class Login < ApplicationRecord
  has_one :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]

end

app/models/managefile.rb
class Managefile < ApplicationRecord
  belongs_to :incidentmanagement
end

app/models/role.rb
class Role < ApplicationRecord
    validates :name, uniqueness: true
    validates :name, :presence => true
    has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :name, :presence => true
  validates :name, uniqueness: true
  validates :email, :presence => true
  validates :email, uniqueness: true
  validates :username, :presence => true
  validates :password, :presence => true
  validates :change_password, :presence => true
  belongs_to :role
  belongs_to :login
  has_many :userclients
  has_many :userapplications
  has_many :userareas
  has_many :applicationoperators
  has_many :incidents
  has_many :incidentmanagements
end

app/models/userarea.rb
class Userarea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/userclient.rb
class Userclient < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :user,  uniqueness: true
  belongs_to :client
  belongs_to :user
end

app/models/vistacliente.rb
class Vistacliente < ApplicationRecord
  
end

app/models/vistagestion.rb
class Vistagestion < ApplicationRecord
  
end

app/models/vistareporte.rb
class Vistareporte < ApplicationRecord
  
end

app/models/vistarole.rb
class Vistarole < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    #
    before_action :authenticate_login!
  
  
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.page(params[:page]).per(5)
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to applications_path(@application), notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to applications_path(@application), notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :state, :page)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_form.html.erb
<br/><br/><br/>
<div class="container">
  <!-- The Modal -->
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
 <!-- Modal Header -->
    <div class="modal-header">
      <h4 class="modal-title"><kbd>Registro de aplicaciones</kbd></h4>
    </div>
<!-- Modal body -->
  <div class="modal-body">
    <div class="modal-content tabcontent">
        <div class="dialog">
  <%= simple_form_for(@application) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <form class="form-inline">
          <label class="form-group col-md-4">
             <%= f.input :name, class: "form-control mb-2 mr-sm-2" %>
          </label>

          <label class="form-group col-md-4">
              <%= f.label :state%>
              <%= f.select :state, options_for_select([['Activo', true], ['Inactivo', false]]) %>
          </label>

        <label class="form-group">
          <%= f.submit "Guardar", class: "btn btn-info btn-md " %>
         </label>

         <label class="form-group">
           <%= link_to 'Regresar', applications_path, class: "btn btn-info btn-md" %>
        </label>
        
      <% end %>
</form>
       </div>
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/applications/edit.html.erb
<%= render 'form', application: @application %>

app/views/applications/index.html.erb
<br/><br/><br/>
  <h1 style="color: #6c757d;">Configuración</h1>
    <div class="tab">
    <button class="tablinks active" onclick="openLink(event, 'Aplicaciones')"><%= link_to 'Aplicaciones', applications_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Areas')"><%= link_to 'Areas', areas_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Criticidades')"><%= link_to 'Criticidad', criticalities_path, style: "color:rgb(23, 162, 184);" %></button>
  </div>
<br/>
<%= notice%>
 <br/><br/>

    <div class="footer">
      <%= link_to 'Nuevo', new_application_path, class: "btn btn-info" %>
    </div><br/>
    
<div id="Aplicaciones" class="modal-content text-center tabcontent">
<div class="table-responsive">
<table class="table">
  <thead>
  <div class="row">
    <tr class="alert alert-secondary justify-content-center">
      <th colspan="3">Id</th>
      <th>Nombre Aplicación</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
    </div>
  </thead>

  <% @applications.each do |application| %>

  <tbody>
    <div class="row">
      <tr class="text-center">
        <td colspan="3"><kbd><%= application.id %></kbd></td>
        <td><%= application.name %></td>
        <td>
          <% if application.state %>           
             <img src="/img/estado_activo_24.png" alt="Activo" />
          <% else %>           
             <img src="/img/estado_falso_24.png" alt="Inactivo" />
          <% end %>
        </td>
        <td>
          <%= link_to edit_application_path(application) do %>
            <%= image_tag "/img/edit_24.png", :title=>"Editar" %>
          <% end %>
          &nbsp; &nbsp;
           <%= link_to application, method: :delete, data: { confirm: 'Are you sure?', remote: true } do %>
                <%= image_tag "/img/eliminar_24.png", :title=>"Eliminar" %>
           <% end %>
        </td>
      </tr>
      </div>
    </tbody>

    <% end %>
  
</table>
</div>
</div>
<div id="spacing">
<%= paginate(@applications) %>
</div>

app/views/applications/new.html.erb
<%= render 'form', application: @application %>

app/views/applications/show.html.erb
</br>

<div class="alert">
  <p id="notice" class="alert alert-success">
    <%= notice %>
      <strong>Aplicación!</strong> Actualizado. 
  </p>
</div>

<div class="modal-content text-center tabcontent">
<div class="table-responsive">
  <table class="table">

    <thead>
      <div class="row">
        <tr class="success btn-info active justify-content-center">
          <th colspan="2">Id</th>
          <th>Nombre Aplicación</th>
          <th>Estado</th>
        </tr>
      </div>
    </thead>

    <tbody>
      <div class="row">
      <tr class="text-center">
        <td colspan="2"><%= @application.id%></td>
        <td><%= @application.name %></td>
        <td><%= @application.state %></td>
        </tr>
      </div>
    </tbody>
  </table>
</div>
</div>

<div class="actions">
</br>
<% comment= link_to 'Editar', edit_application_path(@application) %>
<%= link_to 'Regresar', applications_path, class: "btn btn-info" %>
</div>