config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"
  get 'welcome/index'
  resources :managefiles
  resources :incidentmanagements
  resources :incidentfiles
  resources :incidents
  resources :criticalities
  resources :applicationoperators
  resources :userareas
  resources :userapplications
  resources :applicationclients
  resources :areas
  resources :applications
  resources :userclients
  resources :clients
  resources :users
  resources :roles
  resources :vistaroles
  resources :vistaclientes
  resources :vistareportes
  resources :vistagestions
  get '/user/client/:id', to: 'users#user_client_index', as: "user_client_index"
  post '/user/client/:id', to: 'users#user_client_create', as: "user_client_create"
  get '/user/client/delete/:id', to: 'users#user_client_destroy', as: "user_client_destroy"

  get '/user/area/:id', to: 'users#user_area_index', as: "user_area_index"
  post '/user/area/:id', to: 'users#user_area_create', as: "user_area_create"
  get '/user/area/delete/:id', to: 'users#user_area_destroy', as: "user_area_destroy"
  
  get '/user/application/:id', to: 'users#user_application_index', as: "user_application_index"
  post '/user/application/:id', to: 'users#user_application_create', as: "user_application_create"
  get '/user/application/delete/:id', to: 'users#user_application_destroy', as: "user_application_destroy"

  get '/application/operator/:id', to: 'users#application_operator_index', as: "application_operator_index"
  post '/application/operator/:id', to: 'users#application_operator_create', as: "application_operator_create"
  get '/application/operator/delete/:id', to: 'users#application_operator_destroy', as: "application_operator_destroy"

  get '/client/application_client/:id', to: 'clients#client_application_client_index', as: "client_application_client_index"
  post '/client/application_client/:id', to: 'clients#client_application_client_create', as: "client_application_client_create"
  get '/client/application_client/delete/:id', to: 'clients#client_application_client_destroy', as: "client_application_client_destroy"

  devise_for :logins, controllers: {
    sessions: 'logins/sessions',
    registrations: 'logins/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :applicationclients
    has_many :applicationoperators
end

app/models/applicationclient.rb
class Applicationclient < ApplicationRecord
  
  belongs_to :application
  belongs_to :client
  has_many :userapplications
end

app/models/area.rb
class Area < ApplicationRecord
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :userareas
    has_many :incidents
end

app/models/client.rb
class Client < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    validates :name, :presence => true
    validates :nit, :presence => true
    validates :addres, :presence => true
    validates :telephone, :presence => true
    validates :nit, uniqueness: true
    validates :name, uniqueness: true
    has_many :userclients
    has_many :applicationclients
    has_many :userapplications
end

app/models/criticality.rb
class Criticality < ApplicationRecord

    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :incidents
    has_many :criticalities
end

app/models/incident.rb
class Incident < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :datereport, :presence => true
  validates :description, :presence => true
  belongs_to :area
  belongs_to :userapplication
  belongs_to :user
  belongs_to :criticality
  has_many :incidentfiles
  has_many :incidentmanagements
end

app/models/incidentfile.rb
class Incidentfile < ApplicationRecord
  belongs_to :incident
end

app/models/login.rb
class Login < ApplicationRecord
  has_one :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]

end

app/models/managefile.rb
class Managefile < ApplicationRecord
  belongs_to :incidentmanagement
end

app/models/role.rb
class Role < ApplicationRecord
    validates :name, uniqueness: true
    validates :name, :presence => true
    has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :name, :presence => true
  validates :name, uniqueness: true
  validates :email, :presence => true
  validates :email, uniqueness: true
  validates :username, :presence => true
  validates :password, :presence => true
  validates :change_password, :presence => true
  belongs_to :role
  belongs_to :login
  has_many :userclients
  has_many :userapplications
  has_many :userareas
  has_many :applicationoperators
  has_many :incidents
  has_many :incidentmanagements
end

app/models/userarea.rb
class Userarea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/userclient.rb
class Userclient < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :user,  uniqueness: true
  belongs_to :client
  belongs_to :user
end

app/models/vistacliente.rb
class Vistacliente < ApplicationRecord
  
end

app/models/vistagestion.rb
class Vistagestion < ApplicationRecord
  
end

app/models/vistareporte.rb
class Vistareporte < ApplicationRecord
  
end

app/models/vistarole.rb
class Vistarole < ApplicationRecord
  
end

app/controllers/applicationclients_controller.rb
class ApplicationclientsController < ApplicationController
  before_action :set_applicationclient, only: [:show, :edit, :update, :destroy]

  # GET /applicationclients
  # GET /applicationclients.json
  def index
    @applicationclients = Applicationclient.all
  end

  # GET /applicationclients/1
  # GET /applicationclients/1.json
  def show
  end

  # GET /applicationclients/new
  def new
    @applicationclient = Applicationclient.new
  end

  # GET /applicationclients/1/edit
  def edit
  end

  # POST /applicationclients
  # POST /applicationclients.json
  def create
    @applicationclient = Applicationclient.new(applicationclient_params)

    respond_to do |format|
      if @applicationclient.save
        format.html { redirect_to @applicationclient, notice: 'Applicationclient was successfully created.' }
        format.json { render :show, status: :created, location: @applicationclient }
      else
        format.html { render :new }
        format.json { render json: @applicationclient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicationclients/1
  # PATCH/PUT /applicationclients/1.json
  def update
    respond_to do |format|
      if @applicationclient.update(applicationclient_params)
        format.html { redirect_to @applicationclient, notice: 'Applicationclient was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicationclient }
      else
        format.html { render :edit }
        format.json { render json: @applicationclient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicationclients/1
  # DELETE /applicationclients/1.json
  def destroy
    @applicationclient.destroy
    respond_to do |format|
      format.html { redirect_to applicationclients_url, notice: 'Applicationclient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicationclient
      @applicationclient = Applicationclient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicationclient_params
      params.require(:applicationclient).permit(:user_id, :application_id, :client_id, :servicelevel, :state)
    end
end

app/helpers/applicationclients_helper.rb
module ApplicationclientsHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applicationclients/_form.html.erb
<br/><br/><br/>
<div class="modal-content tabcontent">
  <div class="dialog">
  <%= simple_form_for(@applicationclient) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
        <div class="body">
        
          <div class="form-group">
          <%= f.association :application, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.association :client, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.input :servicelevel, class: "form-control input-lg" %>
          </div>
          

          <div class="form-group">
          <%= f.label :state%>
          <%= f.select :state, options_for_select([['Activo', true], ['Inactivo', false]]) %>
          </div>

        </div>

        <div class="footer">
          <%= f.submit "Guardar", class: "btn btn-primary btn-lg btn-block" %>
          </br>
          <%= link_to 'Regresar', applicationclients_path, class: "btn btn-info btn-lg btn-block" %>
        </div>
        
      <% end %>

    </div>
  </div>

app/views/applicationclients/edit.html.erb
<%= render 'form', applicationclient: @applicationclient %>

app/views/applicationclients/index.html.erb
<br/><br/><br/>
  <h1 style="color: #6c757d;">Configuración</h1>
    <div class="tab">
    <button class="tablinks" onclick="openLink(event, 'Aplicaciones')"><%= link_to 'Aplicaciones', applications_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Areas')"><%= link_to 'Areas', areas_path, style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks active" onclick="openLink(event, 'Nservicios')"><%= link_to 'Aplicación cliente ANS', style: "color:rgb(23, 162, 184);" %></button>
    <button class="tablinks" onclick="openLink(event, 'Criticidades')"><%= link_to 'Criticidad', criticalities_path, style: "color:rgb(23, 162, 184);" %></button>
  </div>
<br/>
<%= notice%>
<br/><br/>

<div class="row">
<div class="col-sm-8">
  <div id="Nservicios" class="modal-content text-center tabcontent">
    <div class="table-responsive">
     <table class="table">
      <thead>
     <div class="row">
     <tr class="alert alert-secondary justify-content-center">
        <th colspan="3">Id</th>
            <th>Nit</th> 
            <th>Nombre</th> 
            <th>Razón</th>   
            <th>Dirección</th>
            <th>Teléfono</th>  
            <th>Contacto</th> 
            <th>Estado</th> 
      </tr>
      </div>
    </thead>
      <tbody>
      <div class="row">
          <tr class="text-center">
            <td colspan="3"><kbd><%= @client.id %></kbd></td>
            <td><%= @client.nit %></td> 
            <td><%= @client.name %></td> 
            <td><%= @client.reason %></td> 
            <td><%= @client.addres %></td> 
            <td><%= @client.telephone %></td> 
            <td><%= @client.contact %></td>
            <td>
        <% if @client.state %>
            <img src="/img/estado_activo_24.png" alt="Activo" />
        <% else %>
            <img src="/img/estado_falso_24.png" alt="Inactivo" />
        <% end %>
      </td>
          </tr>
          </div>
      </tbody>
  </table>
</div>
</div>
</div>
</div>

 <p class="divider"></p>

<div class="row">
<div class="col-sm-8"> 
<div id="Nservicios" class="modal-content text-center tabcontent">
<div class="table-responsive">
<table class="table">
  <thead>
  <div class="row">
    <tr class="alert alert-secondary justify-content-center">
      <th colspan="3">Id</th>
      <th>Aplicación</th>
      <th>Cliente</th>
      <th>Nivel Servicio</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
    </div>
  </thead>

  <% @clientapplicationclients.each do |applicationclient| %>

  <tbody>
    <div class="row">
      <tr class="text-center">
        <td colspan="3"><kbd><%= applicationclient.id %></kbd></td>
        <td><%= applicationclient.application.name %></td>
        <td><%= applicationclient.client.name %></td>
        <td><%= applicationclient.servicelevel %></td>
        <td>
          <% if applicationclient.state %>           
             <img src="/img/estado_activo_24.png" alt="Activo" />
          <% else %>           
             <img src="/img/estado_falso_24.png" alt="Inactivo" />
          <% end %>
        </td>

        <td>
          <%= link_to edit_applicationclient_path(applicationclient) do %>
            <%= image_tag "/img/edit_24.png", :title=>"Editar" %>
          <% end %>
          &nbsp; &nbsp;
           <%= link_to applicationclient, method: :delete, data: { confirm: 'Are you sure?', remote: true } do %>
                <%= image_tag "/img/eliminar_24.png", :title=>"Eliminar" %>
           <% end %>
           </td>
        </tr>
      </div>
      </tbody>

    <% end %>
  
</table>
</div>
</div>
</div>

<div class="col-sm-4"> 
<div class="card">
<div class="card-header">Acciones</div>
<div class="card-body">

  <%= form_for @applicationclient, url: client_application_client_create_path do |f| %>
    <%= f.hidden_field :user_id, :value => 1%>
     <%= f.hidden_field :client_id, :value => @client.id%>
    <%= f.hidden_field :state, :value => true%>

    <label class="form-group">
    <%= f.label :application %>
    <%= f.select :application_id, options_for_select(@applications.collect{ |application| [application.name, application.id] })%>
    </label>
    
    <label class="form-group">
          <%= f.label :servicelevel %>
          <%= f.number_field :servicelevel, :value => 1, min: 1, max: 80, step: 1 %>
        </label>
    <br/><br/>
    <%= f.submit "Guardar", class: "btn btn-info btn-block" %>
    <%= link_to 'Regresar', clients_path, class: "btn btn-dark btn-block" %>
  <% end %>

</div>
</div>
</div>
</div>

app/views/applicationclients/new.html.erb
<%= render 'form', applicationclient: @applicationclient %>

app/views/applicationclients/show.html.erb
<br/><br/><br/>
<div class="modal-content text-center tabcontent">
<div class="table-responsive">
  <table class="table">

    <thead>
      <div class="row">
        <tr class="success btn-info active justify-content-center">
          <th colspan="2">Id</th>
          <th>Nombre Aplicación</th>
          <th>Cliente</th>
          <th>Nivel Servicio</th>
          <th>Estado</th>
        </tr>
      </div>
    </thead>

    <tbody>
      <div class="row">
      <tr class="text-center">
        <td colspan="2"><%= @applicationclient.id%></td>
        <td><%= @applicationclient.application.name %></td>
        <td><%= @applicationclient.client.name %></td>
        <td><%= @applicationclient.servicelevel %></td>
        <td><%= @applicationclient.state %></td>
        </tr>
      </div>
    </tbody>
  </table>
</div>
</div>

<div class="actions">
</br>
<% comment= link_to 'Editar', edit_applicationclient_path(@applicationclient) %>
<%= link_to 'Regresar', applicationclients_path, class: "btn btn-info" %>
</div>