config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"
  get 'welcome/index'
  resources :managefiles
  resources :incidentmanagements
  resources :incidentfiles
  resources :incidents
  resources :criticalities
  resources :applicationoperators
  resources :userareas
  resources :userapplications
  resources :applicationclients
  resources :areas
  resources :applications
  resources :userclients
  resources :clients
  resources :users
  resources :roles
  resources :vistaroles
  resources :vistaclientes
  resources :vistareportes
  resources :vistagestions
  get '/user/client/:id', to: 'users#user_client_index', as: "user_client_index"
  post '/user/client/:id', to: 'users#user_client_create', as: "user_client_create"
  get '/user/client/delete/:id', to: 'users#user_client_destroy', as: "user_client_destroy"

  get '/user/area/:id', to: 'users#user_area_index', as: "user_area_index"
  post '/user/area/:id', to: 'users#user_area_create', as: "user_area_create"
  get '/user/area/delete/:id', to: 'users#user_area_destroy', as: "user_area_destroy"
  
  get '/user/application/:id', to: 'users#user_application_index', as: "user_application_index"
  post '/user/application/:id', to: 'users#user_application_create', as: "user_application_create"
  get '/user/application/delete/:id', to: 'users#user_application_destroy', as: "user_application_destroy"

  get '/application/operator/:id', to: 'users#application_operator_index', as: "application_operator_index"
  post '/application/operator/:id', to: 'users#application_operator_create', as: "application_operator_create"
  get '/application/operator/delete/:id', to: 'users#application_operator_destroy', as: "application_operator_destroy"

  get '/client/application_client/:id', to: 'clients#client_application_client_index', as: "client_application_client_index"
  post '/client/application_client/:id', to: 'clients#client_application_client_create', as: "client_application_client_create"
  get '/client/application_client/delete/:id', to: 'clients#client_application_client_destroy', as: "client_application_client_destroy"

  devise_for :logins, controllers: {
    sessions: 'logins/sessions',
    registrations: 'logins/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :applicationclients
    has_many :applicationoperators
end

app/models/area.rb
class Area < ApplicationRecord
    
    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :userareas
    has_many :incidents
end

app/models/client.rb
class Client < ApplicationRecord
    paginates_per 5
    max_paginates_per 100
    validates :name, :presence => true
    validates :nit, :presence => true
    validates :addres, :presence => true
    validates :telephone, :presence => true
    validates :nit, uniqueness: true
    validates :name, uniqueness: true
    has_many :userclients
    has_many :applicationclients
    has_many :userapplications
end

app/models/criticality.rb
class Criticality < ApplicationRecord

    validates :name, uniqueness: true
    validates :name, :presence => true
    
    has_many :incidents
    has_many :criticalities
end

app/models/incident.rb
class Incident < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :datereport, :presence => true
  validates :description, :presence => true
  belongs_to :area
  belongs_to :userapplication
  belongs_to :user
  belongs_to :criticality
  has_many :incidentfiles
  has_many :incidentmanagements
end

app/models/incidentfile.rb
class Incidentfile < ApplicationRecord
  belongs_to :incident
end

app/models/login.rb
class Login < ApplicationRecord
  has_one :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:username]

end

app/models/managefile.rb
class Managefile < ApplicationRecord
  belongs_to :incidentmanagement
end

app/models/role.rb
class Role < ApplicationRecord
    validates :name, uniqueness: true
    validates :name, :presence => true
    has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :name, :presence => true
  validates :name, uniqueness: true
  validates :email, :presence => true
  validates :email, uniqueness: true
  validates :username, :presence => true
  validates :password, :presence => true
  validates :change_password, :presence => true
  belongs_to :role
  belongs_to :login
  has_many :userclients
  has_many :userapplications
  has_many :userareas
  has_many :applicationoperators
  has_many :incidents
  has_many :incidentmanagements
end

app/models/userarea.rb
class Userarea < ApplicationRecord
  belongs_to :user
  belongs_to :area
end

app/models/userclient.rb
class Userclient < ApplicationRecord
  paginates_per 5
  max_paginates_per 100
  validates :user,  uniqueness: true
  belongs_to :client
  belongs_to :user
end

app/models/vistacliente.rb
class Vistacliente < ApplicationRecord
  
end

app/models/vistagestion.rb
class Vistagestion < ApplicationRecord
  
end

app/models/vistareporte.rb
class Vistareporte < ApplicationRecord
  
end

app/models/vistarole.rb
class Vistarole < ApplicationRecord
  
end

app/controllers/userclients_controller.rb
class UserclientsController < ApplicationController
  before_action :set_userclient, only: [:show, :edit, :update, :destroy]

  # GET /userclients
  # GET /userclients.json
  def index
    @userclients = Userclient.page(params[:page]).per(5)
    @clients = Client.all
    
  end

  # GET /userclients/1
  # GET /userclients/1.json
  def show
  end

  # GET /userclients/new
  def new
    @userclient = Userclient.new
  end

  # GET /userclients/1/edit
  def edit
  end

  # POST /userclients
  # POST /userclients.json
  def create
    @userclient = Userclient.new(userclient_params)
    Rails.logger.debug("ID Usuario: #{@userclient.user.name}")
    
      if @userclient.save
       render json: @userclient
      else
        render :index, notice: "Error"
      end
   
  end

  # PATCH/PUT /userclients/1
  # PATCH/PUT /userclients/1.json
  def update
    respond_to do |format|
      if @userclient.update(userclient_params)
        format.html { redirect_to @userclient, notice: 'Userclient was successfully updated.' }
        format.json { render :show, status: :ok, location: @userclient }
      else
        format.html { render :edit }
        format.json { render json: @userclient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userclients/1
  # DELETE /userclients/1.json
  def destroy
   
    @userclient.destroy
    respond_to do |format|
      format.html { redirect_to user_client_index_path(), notice: 'Userclient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userclient
      @userclient = Userclient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userclient_params
      params.require(:userclient).permit(:client_id, :user_id, :state, :page)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/userclients_helper.rb
module UserclientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/userclients/_form.html.erb
<br/><br/><br/>
<div class="modal-content tabcontent">
  <div class="dialog">
        <%= simple_form_for(@userclient) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="body">
        <div class="form-group">
          <%= f.association :user, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.association :user, label_method: :username, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.association :user, label_method: :role_id, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.association :user, label_method: :mail, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.label :state%>
          <%= f.select :state, options_for_select([['Activo', true], ['Inactivo', false]]) %>
          </div>

          <div class="form-group">
          <%= f.association :client, class: "form-control input-lg" %>
          </div>

          <div class="form-group">
          <%= f.association :user, label_method: :creator, class: "form-control input-lg" %>
          </div>

        </div>

        <div class="footer">
          <%= f.submit "Guardar", class: "btn btn-primary btn-lg btn-block" %>
          </br>
          <%= link_to 'Regresar', userclients_path, class: "btn btn-info btn-lg btn-block" %>
        </div>
        
      <% end %>

    </div>
  </div>

app/views/userclients/edit.html.erb
<%= render 'form', userclient: @userclient %>

app/views/userclients/index.html.erb
<br/><br/><br/>
<h1 style="color: #6c757d;">Configuración</h1>
<div class="tab">
<button class="tablinks" onclick="openLink(event, 'Aplicaciones')"><%= link_to 'Aplicaciones', applications_path, style: "color:rgb(23, 162, 184);" %></button>
<button class="tablinks" onclick="openLink(event, 'Areas')"><%= link_to 'Areas', areas_path, style: "color:rgb(23, 162, 184);" %></button>
<button class="tablinks active" onclick="openLink(event, 'Userclient')"><%= link_to 'Usuario cliente', style: "color:rgb(23, 162, 184);" %></button>
<button class="tablinks" onclick="openLink(event, 'Criticidades')"><%= link_to 'Criticidad', criticalities_path, style: "color:rgb(23, 162, 184);" %></button>
</div>
<br/>
<%= notice%>
<br/><br/>

<div class="row">
<div class="col-sm-8">
  <div id="Nservicios" class="modal-content text-center tabcontent">
    <div class="table-responsive">
     <table class="table">
      <thead>
     <div class="row">
     <tr class="alert alert-secondary justify-content-center">
        <th colspan="3">Id</th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Nombre usuario</th>
            <th>Role</th>
            <th>Estado</th>
      </tr>
      </div>
    </thead>
      <tbody>          
          <tr class="text-center">
            <td colspan="3"><kbd><%= @user.id %></kbd></td>
            <td><%= @user.name %></td>
            <td><%= @user.email %></td>
            <td><%= @user.username %></td>
            <td><%= @user.role.name %></td>
            <td>
                <% if @user.state %>           
                  <img src="/img/estado_activo_24.png" alt="Activo" />
                <% else %>           
                  <img src="/img/estado_falso_24.png" alt="Inactivo" />
                <% end %>
        </td>
          </tr>            
      </tbody>
</table>
</div>
</div>
</div>
</div>

 <p class="divider"></p>

<div class="row">
<div class="col-sm-8"> 
<div id="Uclientes" class="modal-content text-center tabcontent">
<div class="table-responsive">
<table class="table">
<thead>
<tr class="alert alert-secondary justify-content-center">
<th colspan="3">Id</th>
<th>Cliente</th>
<th>Usuario encargado</th>
<th>Estado</th>
<th>Acciones</th>
</tr>
</thead>

<% @userclients.each do |userclient| %>

<tbody>
<tr class="text-center">
<td colspan="3"><kbd><%= userclient.id %></kbd></td>
<td><%= userclient.client.name %></td>
<td><%= userclient.user.name %></td>
<td>
  <% if userclient.state %>           
      <img src="/img/estado_activo_24.png" alt="Activo" />
  <% else %>           
      <img src="/img/estado_falso_24.png" alt="Inactivo" />
  <% end %>
</td>
<td>
  <%= link_to userclient, method: :delete, data: { confirm: 'Are you sure?', remote: true } do %>
    <%= image_tag "/img/eliminar_24.png", :title=>"Eliminar" %>
      <% end %>
  </td>
</tr>
</tbody>

<% end %>

</table>
</div>
</div>
</div>

<div class="col-sm-4"> 
<div class="card">
<div class="card-header">Acciones</div>
<div class="card-body">
  <%= form_for @userclient, url: user_client_create_path do |f| %>

     <%= f.hidden_field :user_id, :value => @user.id%>
    <%= f.hidden_field :state, :value => true%>

  <label class="form-group">
    <%= f.label :client %>
    <%= f.select :client_id, options_for_select(@clients.collect{ |client| [client.name, client.id] })%>
  </label>

    <br/><br/>

    <%= f.submit "Guardar", class: "btn btn-info btn-block" %>
    <%= link_to 'Regresar', users_path, class: "btn btn-dark btn-block" %>
  <% end %>

</div>
</div>
</div>
</div>

app/views/userclients/new.html.erb
<%= render 'form', userclient: @userclient %>

app/views/userclients/show.html.erb
</br>

<div class="alert">
  <p id="notice" class="alert alert-success">
    <%= notice %>
      <strong>Usuario cliente!</strong> Actualizado. 
  </p>
</div>

<div class="modal-content text-center tabcontent">
<div class="table-responsive">
  <table class="table">

    <thead>
      <div class="row">
        <tr class="success btn-info active justify-content-center">
          <th colspan="3">Id</th>
          <th>Usuario Encargado</th>
          <th>Nombre Usuario</th>
          <th>Role</th>
          <th>Cliente</th>
          <th>Estado</th>
          <th>Responsable</th>
        </tr>
      </div>
    </thead>

    <tbody>
      <div class="row">
      <tr class="text-center">
        <td colspan="3"><%= @userclient.id%></td>
        <td><%= @userclient.user.name %></td>
        <td><%= @userclient.user.username %></td>
        <td><%= @userclient.user.role_id %></td>
        <td><%= @userclient.client.name %></td>
        <td><%= @userclient.state %></td>
        <td><%= @userclient.user.creator %></td>
        </tr>
      </div>
    </tbody>
  </table>
</div>
</div>

<div class="actions">
</br>
<% comment= link_to 'Editar', edit_userclient_path(@userclient) %>
<%= link_to 'Regresar', userclients_path, class: "btn btn-info" %>
</div>